services:
  mongodb:
    image: mongo:8.0
    container_name: ozmap-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ozmap
    command: ['mongod', '--quiet']
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/ozmap --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 120s
volumes:
  mongodb_data:
    driver: local
